# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyGenesisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PyGenesisGUI(object):
    def setupUi(self, PyGenesisGUI):
        PyGenesisGUI.setObjectName("PyGenesisGUI")
        PyGenesisGUI.resize(1312, 1003)
        self.centralwidget = QtWidgets.QWidget(PyGenesisGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.PlotCommand = QtWidgets.QLineEdit(self.centralwidget)
        self.PlotCommand.setObjectName("PlotCommand")
        self.verticalLayout_2.addWidget(self.PlotCommand)
        self.DataBrowser = QtWidgets.QTreeWidget(self.centralwidget)
        self.DataBrowser.setObjectName("DataBrowser")
        self.verticalLayout_2.addWidget(self.DataBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.UIReplot = QtWidgets.QPushButton(self.centralwidget)
        self.UIReplot.setObjectName("UIReplot")
        self.verticalLayout.addWidget(self.UIReplot)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.UIPos = QtWidgets.QSlider(self.centralwidget)
        self.UIPos.setMaximum(100)
        self.UIPos.setOrientation(QtCore.Qt.Horizontal)
        self.UIPos.setObjectName("UIPos")
        self.verticalLayout.addWidget(self.UIPos)
        self.UILegend = QtWidgets.QCheckBox(self.centralwidget)
        self.UILegend.setObjectName("UILegend")
        self.verticalLayout.addWidget(self.UILegend)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.UIYLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.UIYLabel.setObjectName("UIYLabel")
        self.verticalLayout.addWidget(self.UIYLabel)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.UITitle = QtWidgets.QLineEdit(self.centralwidget)
        self.UITitle.setObjectName("UITitle")
        self.verticalLayout.addWidget(self.UITitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.UIXmin = QtWidgets.QLineEdit(self.centralwidget)
        self.UIXmin.setObjectName("UIXmin")
        self.gridLayout.addWidget(self.UIXmin, 1, 0, 1, 1)
        self.UIXmax = QtWidgets.QLineEdit(self.centralwidget)
        self.UIXmax.setObjectName("UIXmax")
        self.gridLayout.addWidget(self.UIXmax, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.UIYmax = QtWidgets.QLineEdit(self.centralwidget)
        self.UIYmax.setObjectName("UIYmax")
        self.gridLayout.addWidget(self.UIYmax, 3, 1, 1, 1)
        self.UIYmin = QtWidgets.QLineEdit(self.centralwidget)
        self.UIYmin.setObjectName("UIYmin")
        self.gridLayout.addWidget(self.UIYmin, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.DatasetList = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DatasetList.sizePolicy().hasHeightForWidth())
        self.DatasetList.setSizePolicy(sizePolicy)
        self.DatasetList.setObjectName("DatasetList")
        self.DatasetList.setColumnCount(0)
        self.DatasetList.setRowCount(0)
        self.verticalLayout_3.addWidget(self.DatasetList)
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setMinimumSize(QtCore.QSize(1000, 700))
        self.mplwindow.setObjectName("mplwindow")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mplwindow)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mplvl = QtWidgets.QVBoxLayout()
        self.mplvl.setObjectName("mplvl")
        self.verticalLayout_4.addLayout(self.mplvl)
        self.verticalLayout_3.addWidget(self.mplwindow)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        PyGenesisGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PyGenesisGUI)
        self.statusbar.setObjectName("statusbar")
        PyGenesisGUI.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PyGenesisGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuColor_Scales = QtWidgets.QMenu(self.menuPlot)
        self.menuColor_Scales.setObjectName("menuColor_Scales")
        PyGenesisGUI.setMenuBar(self.menubar)
        self.actionLoad = QtWidgets.QAction(PyGenesisGUI)
        self.actionLoad.setObjectName("actionLoad")
        self.actionReload = QtWidgets.QAction(PyGenesisGUI)
        self.actionReload.setObjectName("actionReload")
        self.actionClose = QtWidgets.QAction(PyGenesisGUI)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(PyGenesisGUI)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDelete = QtWidgets.QAction(PyGenesisGUI)
        self.actionDelete.setObjectName("actionDelete")
        self.actionDuplicate = QtWidgets.QAction(PyGenesisGUI)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.actionCor1 = QtWidgets.QAction(PyGenesisGUI)
        self.actionCor1.setObjectName("actionCor1")
        self.actionCor2 = QtWidgets.QAction(PyGenesisGUI)
        self.actionCor2.setObjectName("actionCor2")
        self.actionAutocorrelation = QtWidgets.QAction(PyGenesisGUI)
        self.actionAutocorrelation.setObjectName("actionAutocorrelation")
        self.actionWigner = QtWidgets.QAction(PyGenesisGUI)
        self.actionWigner.setObjectName("actionWigner")
        self.actionviridis = QtWidgets.QAction(PyGenesisGUI)
        self.actionviridis.setCheckable(False)
        self.actionviridis.setChecked(False)
        self.actionviridis.setObjectName("actionviridis")
        self.actionInferno = QtWidgets.QAction(PyGenesisGUI)
        self.actionInferno.setCheckable(False)
        self.actionInferno.setObjectName("actionInferno")
        self.actionSeismic = QtWidgets.QAction(PyGenesisGUI)
        self.actionSeismic.setObjectName("actionSeismic")
        self.actionOcean = QtWidgets.QAction(PyGenesisGUI)
        self.actionOcean.setObjectName("actionOcean")
        self.actionTerrain = QtWidgets.QAction(PyGenesisGUI)
        self.actionTerrain.setObjectName("actionTerrain")
        self.actionJet = QtWidgets.QAction(PyGenesisGUI)
        self.actionJet.setObjectName("actionJet")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuAnalysis.addAction(self.actionCor1)
        self.menuAnalysis.addAction(self.actionCor2)
        self.menuAnalysis.addAction(self.actionAutocorrelation)
        self.menuAnalysis.addAction(self.actionWigner)
        self.menuColor_Scales.addAction(self.actionviridis)
        self.menuColor_Scales.addAction(self.actionInferno)
        self.menuColor_Scales.addAction(self.actionSeismic)
        self.menuColor_Scales.addAction(self.actionOcean)
        self.menuColor_Scales.addAction(self.actionTerrain)
        self.menuColor_Scales.addAction(self.actionJet)
        self.menuPlot.addAction(self.menuColor_Scales.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(PyGenesisGUI)
        self.actionQuit.triggered.connect(PyGenesisGUI.close)
        QtCore.QMetaObject.connectSlotsByName(PyGenesisGUI)

    def retranslateUi(self, PyGenesisGUI):
        _translate = QtCore.QCoreApplication.translate
        PyGenesisGUI.setWindowTitle(_translate("PyGenesisGUI", "Genesis Postprocessor in Python"))
        self.label.setText(_translate("PyGenesisGUI", "Select Datasets (RegExp)"))
        self.DataBrowser.headerItem().setText(0, _translate("PyGenesisGUI", "Files and Datasets"))
        self.UIReplot.setText(_translate("PyGenesisGUI", "Update Plot"))
        self.label_3.setText(_translate("PyGenesisGUI", "Relative Position"))
        self.UILegend.setText(_translate("PyGenesisGUI", "Add Legend"))
        self.label_8.setText(_translate("PyGenesisGUI", "Y-Label"))
        self.label_9.setText(_translate("PyGenesisGUI", "Title"))
        self.label_4.setText(_translate("PyGenesisGUI", "Xmin"))
        self.label_5.setText(_translate("PyGenesisGUI", "Xmax"))
        self.label_6.setText(_translate("PyGenesisGUI", "Ymin"))
        self.label_7.setText(_translate("PyGenesisGUI", "Ymax"))
        self.label_2.setText(_translate("PyGenesisGUI", "Selected Datasets"))
        self.menuFile.setTitle(_translate("PyGenesisGUI", "File"))
        self.menuEdit.setTitle(_translate("PyGenesisGUI", "Edit"))
        self.menuAnalysis.setTitle(_translate("PyGenesisGUI", "Analysis"))
        self.menuPlot.setTitle(_translate("PyGenesisGUI", "Plot"))
        self.menuColor_Scales.setTitle(_translate("PyGenesisGUI", "Colormaps"))
        self.actionLoad.setText(_translate("PyGenesisGUI", "Load File..."))
        self.actionLoad.setShortcut(_translate("PyGenesisGUI", "Ctrl+L"))
        self.actionReload.setText(_translate("PyGenesisGUI", "Reload File"))
        self.actionReload.setShortcut(_translate("PyGenesisGUI", "Ctrl+Shift+L"))
        self.actionClose.setText(_translate("PyGenesisGUI", "Close File"))
        self.actionClose.setShortcut(_translate("PyGenesisGUI", "Ctrl+C"))
        self.actionQuit.setText(_translate("PyGenesisGUI", "Quit"))
        self.actionQuit.setShortcut(_translate("PyGenesisGUI", "Ctrl+Q"))
        self.actionDelete.setText(_translate("PyGenesisGUI", "Delete Dataset"))
        self.actionDelete.setShortcut(_translate("PyGenesisGUI", "Ctrl+X"))
        self.actionDuplicate.setText(_translate("PyGenesisGUI", "Duplicate Dataset"))
        self.actionDuplicate.setShortcut(_translate("PyGenesisGUI", "Ctrl+D"))
        self.actionCor1.setText(_translate("PyGenesisGUI", "Temporal Coherence, 1st order"))
        self.actionCor2.setText(_translate("PyGenesisGUI", "Temporal Coherence, 2nd order"))
        self.actionAutocorrelation.setText(_translate("PyGenesisGUI", "Autocorrelation"))
        self.actionWigner.setText(_translate("PyGenesisGUI", "Wigner Distribution"))
        self.actionviridis.setText(_translate("PyGenesisGUI", "Viridis"))
        self.actionInferno.setText(_translate("PyGenesisGUI", "Inferno"))
        self.actionSeismic.setText(_translate("PyGenesisGUI", "Seismic"))
        self.actionOcean.setText(_translate("PyGenesisGUI", "Ocean"))
        self.actionTerrain.setText(_translate("PyGenesisGUI", "Terrain"))
        self.actionJet.setText(_translate("PyGenesisGUI", "Jet"))

